/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

import com.example.service.Register;
import com.example.service.SalesTaxCalculator;
import com.example.service.TaxCalculator;

public class App {

    public static void main(String[] args) {

        System.out.println("spring-configuration app is starting...");
        
        //  TODO-05: Instantiate the ApplicationContext using AnnotationConfigApplicationContext.
        ApplicationContext spring = new
                AnnotationConfigApplicationContext(Config.class);
        Register registerBean = (Register) spring.getBean("register");
        System.out.print(registerBean.computeTotal(100.00));

        //  TODO-06: Get the Register bean from the ApplicationContext.
        //  Lookup the bean by its name or type - your choice.


        //  TODO-07: Call the computeTotal method on the Register bean.
        //  Pass in a double value of 100.00.
        //  Print the result to the console.

    }


}
